.TH SCREEN_OFF "1" "February 2013" "screen_off 1.0" "User Commands"
.SH NAME
Screen off \- turn the screen off
.SH SYNOPSIS
\fBscreen_off\fR
.SH DESCRIPTION
Turn RaspberryPi's screen off (on hdmi output).
.SH "REPORTING BUGS"
Report bugs to <jd.jdhp@gmail.com>.
.SH COPYRIGHT
Copyright \(co 2013 Jeremie DECOCK (http://www.jdhp.org)
.br
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
